format_version: v1.0
type: UniqueComponent
attributes: {id: cryptoauthlib_kit_host}
children:
- type: Symbols
  children:
  - type: String
    attributes: {id: HAL_INTERFACE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: cryptoauthlib_kit_host, value: SERCOM2_UART}
- type: Attachments
  children:
  - type: DirectDependency
    attributes: {id: UART}
    children:
    - type: Attributes
      children:
      - type: String
        attributes: {id: targetComponentID}
        children:
        - {type: Value, value: sercom2}
      - type: String
        attributes: {id: targetAttachmentID}
        children:
        - {type: Value, value: SERCOM2_UART}
- type: ElementPosition
  attributes: {x: '771', y: '477', id: cryptoauthlib_kit_host}
